[package]
name = "rustwasmhello"
version = "0.1.0"
authors = ["JoshuaHolloway <jhollow6@asu.edu>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

