[package]
name = "rustycheckers"
version = "0.1.0"
authors = ["JoshuaHolloway <jhollow6@asu.edu>"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
